# Generated by Django 3.0.2 on 2020-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='contraseña',
            field=models.CharField(default='', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profesor',
            name='contraseña',
            field=models.CharField(default='0', max_length=8),
            preserve_default=False,
        ),
    ]
