# Generated by Django 3.0.2 on 2020-05-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200420_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='nota_examen1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota_examen2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nota_examen3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_examen1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_examen2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='tiempo_examen3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
